name: Set Branch Protection Rules

on:
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest

    steps:
    - name: Set branch protection rules
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        REPO_NAME="owner/repository-name" # Replace with the actual owner and repository
        BRANCH="main" # Replace with the branch you want to protect

        curl -X PUT \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_NAME/branches/$BRANCH/protection \
          -d '{
            "required_status_checks": {
              "strict": true,
              "contexts": []
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismissal_restrictions": {},
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": 1
            },
            "restrictions": null
          }'